# Generated by Django 6.0.2 on 2026-09-23 13:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('car_make', models.CharField(blank=True, default='', max_length=100)),
                ('car_model', models.CharField(blank=True, default='', max_length=100)),
                ('car_year', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('diagnosed', 'Diagnosed'), ('booked', 'Booked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='chat_uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'File')], default='file', max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_summary', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low - Minor Issue / Maintenance'), ('medium', 'Medium - Inspection Recommended'), ('high', 'High - Immediate Attention Required'), ('critical', 'Critical - Do Not Drive')], default='medium', max_length=20)),
                ('recommended_repair', models.TextField()),
                ('estimated_cost', models.CharField(default='$150 - $350', max_length=100)),
                ('estimated_time', models.CharField(default='1 - 2 hours', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='api.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=30)),
                ('vehicle_info', models.CharField(help_text='e.g. 2018 Toyota Camry 2.5L', max_length=200)),
                ('service_requested', models.TextField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(default='10:00 AM', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.chatsession')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('content', models.TextField()),
                ('is_rejected', models.BooleanField(default=False, help_text='True if query was rejected as off-topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='api.mediaupload')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
