# Generated by Django 6.0.2 on 2026-09-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='car_company',
            field=models.CharField(blank=True, default='', help_text='Car company / manufacturer name (e.g. Toyota)', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='car_model',
            field=models.CharField(blank=True, default='', help_text='Car model name (e.g. Camry)', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_problem',
            field=models.TextField(blank=True, default='', help_text='Specific problem facing in vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_info',
            field=models.CharField(help_text='e.g. 2020 Toyota Camry', max_length=200),
        ),
    ]
