# Generated by Django 6.0.2 on 2026-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_car_company_booking_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='confidence',
            field=models.CharField(default='85%', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='possible_cause',
            field=models.TextField(default='Mechanical component wear or fluid/electrical defect'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='recommended_action',
            field=models.TextField(default='Inspect vehicle components, fluid levels, and diagnostic fault codes'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptoms_detected',
            field=models.TextField(default='✓ Abnormal mechanical noise\n✓ Vehicle performance degradation\n✓ System fault detected'),
        ),
    ]
